#define MK_3_SPEED

#define MK_C_OFFSET_0 8
#define MK_C_OFFSET_1 16
#define MK_C_OFFSET_2 32

#define MK_W_INTERVAL_0 120
#define MK_W_INTERVAL_1 80
#define MK_W_INTERVAL_2 40

#define ONESHOT_TAP_TOGGLE 4
#define ONESHOT_TIMEOUT 5000

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2
