#define MK_3_SPEED

#define MK_C_OFFSET_0 8
#define MK_C_OFFSET_1 16
#define MK_C_OFFSET_2 32

#define MK_W_INTERVAL_0 120
#define MK_W_INTERVAL_1 80
#define MK_W_INTERVAL_2 40

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#define RETRO_TAPPING

#define TAPPING_TERM 500
